version: '3.8'
services:
  petclinic:
    image: eclipse-temurin:17-jdk
    volumes:
      - ./target/${JAR_NAME}:/petclinic/petclinic.jar
    ports:
      - "8080:8080"
    command: ["java", "-jar", "/petclinic/petclinic.jar"]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/petclinic
      - SPRING_DATASOURCE_USERNAME=petclinic
      - SPRING_DATASOURCE_PASSWORD=petclinic
  mysql:
    image: mysql:9.1
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
 # postgres:
  #  image: postgres:17.0
   # ports:
    #  - "5432:5432"
    #environment:
     # - POSTGRES_PASSWORD=petclinic
     # - POSTGRES_USER=petclinic
     # - POSTGRES_DB=petclinic
