version: '3.8'
services:
  petclinic:
    image: eclipse-temurin:17-jdk
    container_name: petclinic_app
    volumes:
      - ./target/${JAR_NAME}:/petclinic/petclinic.jar
    ports:
      - "8080:8080"
    command: ["java", "-jar", "/petclinic/petclinic.jar"]
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/petclinic
      - SPRING_DATASOURCE_USERNAME=petclinic
      - SPRING_DATASOURCE_PASSWORD=petclinic
 # mysql:
  #  image: mysql:9.1
   # container_name: petclinic_sql
   # ports:
    #  - "3306:3306"
    #environment:
     # - MYSQL_ROOT_PASSWORD=
      #- MYSQL_ALLOW_EMPTY_PASSWORD=true
      #- MYSQL_USER=petclinic
      #- MYSQL_PASSWORD=petclinic
      #- MYSQL_DATABASE=petclinic
    #volumes:
    #  - "./conf.d:/etc/mysql/conf.d:ro"
     # - mysql_data:/var/lib/mysql
     # - ./src/main/resources/db/mysql:/docker-entrypoint-initdb.d
#volumes:
 # mysql_data:
  postgres:
    image: postgres:17.0
    container_name: petclinic_postgres
    ports:
      - "5432:5432"
    #environment:
     # - POSTGRES_PASSWORD=petclinic
     # - POSTGRES_USER=petclinic
     # - POSTGRES_DB=petclinic
    volumes:
      - ./src/main/resources/db/postgres:/docker-entrypoint-initdb.d
